services:
  postgres:
    image: 'postgres:latest'
    container_name: bdd-udl
    environment:
      - 'POSTGRES_DB=udl'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: