spring:
  application:
    name: universdesames
  profiles:
    active: dev # Profil par d√©faut = dev

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

google:
  calendar:
    id: "primary"
