spring:
  application:
    name: universdesames
  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

google:
  calendar:
    primary-id: ${GOOGLE_CALENDAR_PRIMARY_ID}
    check-ids: ${GOOGLE_CALENDAR_CHECK_IDS}

stripe:
  secret-key: ${STRIPE_SECRET_KEY}
  public-key: ${STRIPE_PUBLIC_KEY}
