spring:
  application:
    name: universdesames
  profiles:
    active: dev # Profil par défaut = dev

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

google:
  calendar:
    id: "primary"

stripe:
  secret-key: ${STRIPE_SECRET_KEY} # Sera injecté par variable d'env ou Docker Secret
  public-key: ${STRIPE_PUBLIC_KEY}
