spring:
  application:
    name: universdesames
  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

google:
  calendar:
    primary-id: ${GOOGLE_CALENDAR_PRIMARY_ID:0000}
    check-ids: ${GOOGLE_CALENDAR_CHECK_IDS:0000}

stripe:
  secret-key: ${STRIPE_SECRET_KEY:0000}
  public-key: ${STRIPE_PUBLIC_KEY:0000}

aws:
  s3:
    endpoint: ${S3_ENDPOINT}
    public-url: ${S3_PUBLIC_URL}
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
    bucket: ${S3_BUCKET}
    region: ${S3_REGION:eu-west-1} # Par d√©faut us-east-1 pour MinIO
