spring:
  application:
    name: universdesames
  # Configuration de la base de données H2
  datasource:
    url: jdbc:h2:mem:spiritdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # Console H2 pour visualiser tes tables
  h2:
    console:
      enabled: true
      path: /h2-console

  # Configuration JPA / Hibernate
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update # Crée les tables automatiquement selon tes @Entity
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Exécution du fichier data.sql au démarrage
  sql:
    init:
      mode: always

  # Désactivation explicite de Liquibase
  liquibase:
    enabled: false
#  datasource:
#    url: jdbc:postgresql://localhost:5432/udl
#    username: admin
#    password: admin
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: validate
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#
#  liquibase:
#    change-log: classpath:db/changelog/db.changelog-master.xml
#    enabled: true