spring:
  application:
    name: universdesames
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

google:
  calendar:
    id: "primary" # Ou l'ID spécifique de votre calendrier
  credentials:
    path: "credentials.json" # Chemin vers votre fichier JSON (à placer à la racine du projet ou dans resources)
